# Generated by Django 5.0.9 on 2025-04-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInventoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_link', to='dcim.inventoryitem')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_link', to='dcim.module')),
            ],
        ),
    ]
